accounts/urls.py
from django.urls import path
from . import views
from rest_framework.authtoken import views as auth_token

app_name = 'accounts'
urlpatterns = [
    path('register/', views.UserReisterView.as_view(), name="register"),
    path('api-token-auth/', auth_token.obtain_auth_token),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('profile/<int:id>', views.UserProfileView.as_view(), name='profile'),
    path('reset/', views.UserResetPassword.as_view(), name='reset_password'),
    path('follow/<int:user_id>', views.UserFollowView.as_view(), name='follow'),
    path('unfollow/<int:user_id>', views.UserUnfollowView.as_view(), name='unfollow'),
    path('profile/', views.EditProfileView.as_view(), name='edit_profile'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('questions/', views.QuestionView.as_view(), name='questions'),
    path('questions/create/', views.QuestionCreateView.as_view(), name='questions'),
    path('questions/update/<int:pk>', views.QuestionUpdateView.as_view(), name='questions'),
    path('questions/delete/<int:pk>/', views.QuestionDeleteView.as_view(), name='questions'),

    ]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('home.urls'), name='home'),
    path('', include('accounts.urls'), name='accounts'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.db.models.signals import post_save


class Post(models.Model): 
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_posts') 
    body = models.TextField()
    slug = models.SlugField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f'{self.slug} - {self.created}'
    
    
    def get_absolute_url(self):
        return reverse("home:post", args=(self.id, self.slug)) 
    
    def like_counter(self):
        return self.post_votes.count()
    
    
class Relation(models.Model):
    from_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='followers')
    to_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following')
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.from_user} following {self.to_user}'
    
    
    
class Comments(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comment')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_comment')
    reply = models.ForeignKey('self', on_delete=models.CASCADE, related_name='reply_comment', blank=True, null=True) # it is related to Comments model.
    
    is_reply = models.BooleanField(default=False)
    body = models.TextField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.user} - {self.body[:20]}'
    


class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_votes')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_votes')
    
    def __str__(self):
        return f'{self.user} liked {self.post}' 


class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE, null=True, blank=True)
    age = models.SmallIntegerField(default=0)
    bio = models.CharField(max_length=100, null=True, blank=True)
    

home/models.py
from django.db import models
from django.contrib.auth.models import User

class Question(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_qustions')
    title = models.CharField(max_length=100)
    body = models.TextField()
    slug = models.SlugField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.user} - {self.title}'
    
    
class Answer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_answers')
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='question_answers')
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.user} - {self.question.title[:30]}'

home/forms.py
from django import forms
# from .models import mymodel

# class Name(forms.Form):
#     esm = forms.CharField()
#     famil = forms.CharField()
#     tozih = forms.CharField(required=False)


# class update_model(forms.ModelForm):
#     class Meta:
#         model = mymodel
#         fields = ('esm', 'famil')

home/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from rest_framework.views import APIView
from rest_framework.response import Response
from .serializers import *
from django.contrib.auth.models import User
from rest_framework.permissions import IsAdminUser, IsAuthenticated
from rest_framework.renderers import TemplateHTMLRenderer
from .models import *
from rest_framework import status

class Home(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'home/index.html'
    def get(self, request):
        questions = Question.objects.all()
        srz = QuestionSerializer(instance=questions, many=True)
        return Response({'questions':questions})


class QuestionView(APIView):
    permission_classes = [IsAuthenticated]
    
    def get(self, request):
        questions = Question.objects.all()
        srz = QuestionSerializer(instance=questions, many=True)
        
        return Response(srz.data, status=status.HTTP_200_OK)
        
class QuestionCreateView(APIView):
    def post(self, request):
        srz = QuestionSerializer(data=request.data)
        if srz.is_valid():
            srz.save()
            return Response(srz.data, status=status.HTTP_201_CREATED)
        return Response(srz.errors, status=status.HTTP_400_BAD_REQUEST)
    
    
class QuestionUpdateView(APIView):
    def put(self, request, pk):
        question = Question.objects.get(id=pk)
        srz = QuestionSerializer(instance=question, data=request.data, partial=True)
        if srz.is_valid():
            srz.save()
            return Response(srz.data, status=status.HTTP_200_OK)
        return Response(srz.errors, status=status.HTTP_400_BAD_REQUEST)
    
class QuestionDeleteView(APIView):
    def delete(self, request, pk):
        question = Question.objects.get(id=pk)
        question.delete()
        
        return Response({'message':'deleted'}, status=status.HTTP_200_OK)

home/templates/home/create.html
{% extends 'base.html' %}


{% block content %}

<form action="" method="post" novalidate>
{% csrf_token %}

{{ form.as_p }}

<input type="submit" value="Create"> 


</form>

{% endblock %}

home/templates/home/index.html
{% extends 'base.html' %}
{% load rest_framework %}

{% block content %}

<p class='text'> hellooooo </p>

<form action="" method="get">

    {% csrf_token %}

<input type="submit" value="search">

</form>

<div class="card">
    {% for q in questions %}
    <a class="card-body" href="" >{{ q.title }}</a>
    {% endfor %}
</div>

{% comment %} <div class="card">
    {% for post in posts %}
    <a class="card-body" href="{% url 'home:post' post.id post.slug %}" >{{ post.body|truncatewords:2 }}</a>
    {% endfor %}
</div>
 {% endcomment %}



{% endblock %}

home/templates/home/post_view.html
{% extends 'base.html' %} {% block content %}

<div class="card">
  <div class="card-body">
    <a href="{% url 'accounts:profile' post.user.id %}">{{ post.user }}</a> - {{
    post.updated|date:"Y-M" }}
  </div>
  <div class="card-body">{{ post.body }}</div>

</div>

  {% if post.user.id == request.user.id %}

  <a class="btn btn-danger" href="{% url 'home:post_delete' post.id %}">Delete post</a><br>
  <a class="btn btn-info" href="{% url 'home:post_update' post.id %}">Update post</a>

  {% endif %}


  {% if request.user.is_authenticated %}

  <a href="{% url 'home:post_like' post.id %}" class="btn btn-primary col-md-1">{{ post.like_counter }} Like</a>
  
  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send">
  </form>
  {% else %}

  <p> to send comments, please login first </p>

  {% endif %}

  

  {% for comment in comments %}

    <div class="card bg-dark text-white">
        <p class="card-header">{{ comment.user }} | {{ comment.created|timesince }}</p>
        <p class="card-body">{{ comment.body }}</p>




      {% if request.user.is_authenticated %}
      <form action="{% url 'home:reply_comment' post.id comment.id %}" method="post">
        {% csrf_token %}
        {{ form_reply.as_p }}
        <input type="submit" value="Reply">
      </form>
      {% endif %}





        {% with replies=comment.reply_comment.all %}
        {% for reply in commetn.reply_comments.all %}
        <p class="bg">{{ reply.user}} <br/> {{ reply.body }}</p>
        {% endfor %}
        {% endwith %}
    </div>

    {% empty %}
    <p class="card">No Comments</p>
  {% endfor %}


{% endblock %}

home/templates/home/update.html
{% extends 'base.html' %}


{% block content %}

<form action="" method="post" novalidate>
{% csrf_token %}

{{ form.as_p }}

<input type="submit" value="Update">

</form>

{% endblock %}