accounts/urls.py
from django.urls import path
from . import views
from rest_framework.authtoken import views as auth_token

app_name = 'accounts'
urlpatterns = [
    path('register/', views.UserReisterView.as_view(), name="register"),
    path('api-token-auth/', auth_token.obtain_auth_token),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('profile/<int:id>', views.UserProfileView.as_view(), name='profile'),
    path('reset/', views.UserResetPassword.as_view(), name='reset_password'),
    path('follow/<int:user_id>', views.UserFollowView.as_view(), name='follow'),
    path('unfollow/<int:user_id>', views.UserUnfollowView.as_view(), name='unfollow'),
    path('profile/', views.EditProfileView.as_view(), name='edit_profile'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('questions/', views.QuestionView.as_view(), name='questions'),
    path('questions/create/', views.QuestionCreateView.as_view(), name='questions'),
    path('questions/update/<int:pk>', views.QuestionUpdateView.as_view(), name='questions'),
    path('questions/delete/<int:pk>/', views.QuestionDeleteView.as_view(), name='questions'),

    ]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('home.urls'), name='home'),
    path('', include('accounts.urls'), name='accounts'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.db.models.signals import post_save


class Post(models.Model): 
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_posts') 
    body = models.TextField()
    slug = models.SlugField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f'{self.slug} - {self.created}'
    
    
    def get_absolute_url(self):
        return reverse("home:post", args=(self.id, self.slug)) 
    
    def like_counter(self):
        return self.post_votes.count()
    
    
class Relation(models.Model):
    from_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='followers')
    to_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following')
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.from_user} following {self.to_user}'
    
    
    
class Comments(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comment')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_comment')
    reply = models.ForeignKey('self', on_delete=models.CASCADE, related_name='reply_comment', blank=True, null=True) # it is related to Comments model.
    
    is_reply = models.BooleanField(default=False)
    body = models.TextField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.user} - {self.body[:20]}'
    


class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_votes')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_votes')
    
    def __str__(self):
        return f'{self.user} liked {self.post}' 


class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE, null=True, blank=True)
    age = models.SmallIntegerField(default=0)
    bio = models.CharField(max_length=100, null=True, blank=True)
    

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .serializers import *
from rest_framework.permissions import IsAuthenticated
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework import status


class UserReisterView(APIView):
    serializer = UserRegisterSerializer
    # renderer_classes = [TemplateHTMLRenderer]
    # template_name = 'accounts/register.html'
    
    
    def get(self, request):
        srz = self.serializer()
        return Response(srz.data, status=status.HTTP_200_OK)
        
    def post(self, request):
        srz = self.serializer(data=request.POST)
        if srz.is_valid():
            srz.create(srz.validated_data)
            return Response(srz.data, status=status.HTTP_200_OK)
        return Response(srz.errors, status=status.HTTP_400_BAD_REQUEST)
    

class UserLoginView(APIView):
    serializer = UserLoginSerializer
    
    def get(self, request):
        srz = self.serializer()
        return Response(srz.data)

    def post(self, request):
        srz = self.serializer(data=request.POST)
        
        if srz.is_valid():
            vd = srz.validated_data
            user = authenticate(
                request, username=vd['username'], password=vd['password'])
            if user is not None:
                login(request, user)
                Response(srz.data, status = status.HTTP_200_OK)

        return Response(srz.errors, status=status.HTTP_400_BAD_REQUEST)


class UserLogoutView(APIView):
    permission_classes = [IsAuthenticated]
    
    def get(self, request):
        logout(request)

        return Response(status = status.HTTP_200_OK)
    
    
    
class UserProfileView(APIView):

    permission_classes = [IsAuthenticated]
    serializer_pro = ProfileSerializer


    def get(self, request, id):
        is_followig = False
        user = User.objects.get(id=id)
        srz = self.serializer_pro(instance=user)
        
        relation = Relation.objects.filter(from_user = request.user, to_user=user)
        if relation.exists():
            is_followig = True
        
        srz_data = srz.data  
        srz_data['is_following'] = is_followig

        return Response(srz_data, status=status.HTTP_200_OK)
    
    def post(self, request, id):
        form = self.form_class(request.POST)


class UserResetPassword(APIView):
    serializer = PasswordResetSerializer
    
    def get(self, request):
        user = request.user
        srz = self.serializer()
        
        return Response(srz.data, status=status.HTTP_200_OK)
    
    def put(self, requset):
        user = requset.user
        srz = self.serializer(data=requset.data)
        if srz.is_valid():
            user.set_password(srz.data.get('new_password'))
            user.save()
            return Response(data={'message':'ok'}, status=status.HTTP_200_OK)
        return Response(srz.errors, status=status.HTTP_400_BAD_REQUEST)
    
        
    
    
class UserFollowView(APIView):
    
    def get(self, request, user_id):
        user = User.objects.get(id=user_id)
        relatin = Relation.objects.filter(from_user=request.user, to_user=user)
        if relatin.exists():
            return Response({'message':'you already followed this user.'},status=status.HTTP_400_BAD_REQUEST)
            
        Relation(from_user=request.user, to_user=user).save()
        return Response(data={'user_id':user_id ,'message':'you followed this user.'} ,status=status.HTTP_200_OK)

        
        
class UserUnfollowView(APIView):
    def get(self, request, user_id):
        user = User.objects.get(id=user_id)
        relatin = Relation.objects.filter(from_user=request.user, to_user=user)
        if relatin.exists():
            relatin.delete()
            return Response({'message':'user unfollowed.'}, status=status.HTTP_200_OK)
            
        return Response(status=status.HTTP_400_BAD_REQUEST)

        
class EditProfileView(APIView):
    permission_classes = [IsAuthenticated]
    serializer = ProfileEditSerializer
    
    def get(self, request):
        srz = self.serializer(instance=request.user.profile)
        
        return Response(srz.data, status=status.HTTP_200_OK)
    
    def post(self, request):
        srz = self.serializer(data=request.POST)
        prof = Profile.objects.get(user=request.user)
        if srz.is_valid():
            prof.age = srz.data['age']
            prof.bio = srz.data['bio']
            prof.save()

            Response(srz.data, status=status.HTTP_200_OK)
        return Response(srz.errors, status=status.HTTP_400_BAD_REQUEST)
            
        
        

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% load rest_framework %}
{% block content %}

<form action="" method="post" class="text input-box col-md-6" novalidate>
    {% csrf_token %}
    {% render_form form %}
    
    <input type="submit" value="Save" class="text">

</form>


<form class {% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load rest_framework %}

{% block content %}

<form action="" method="post" class="text input-box col-md-6" novalidate>
    {% csrf_token %}
    {% render_form form %}

    <input type="submit" value="Log In" class="text">

</form>


{% endblock %}

accounts/templates/accounts/password_reset.html
{% extends 'base.html' %}


{% block content %}

<form action="" method="post" novalidate>

    {% csrf_token %}

    {{ form.as_p }}

    <input type="submit" value="update password">

</form>

{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %} {% block content %} 

<h2> Password Changed !! </h2>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %} {% block content %} {% if validlink %}

<form action="" method="post">
  {% csrf_token %} {{ form.as_p }}

  <input type="submit" value="update password" />
</form>

{% else %}

<h3>This link is not valid</h3>

{% endif %} {% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}


{% block content %}

<h2> Email is Sent </h2>

{% endblock %}

accounts/templates/accounts/password_reset_email.html
{% extends 'base.html' %}


{% block content %}

please reset your email {{ email }} follow the link:

{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %} {% block content %}

<form action="" method="get">
  {% csrf_token %}

  <h3>{{ user.username }}</h3>

  {{ form.as_p}}

  <input type="submit" value="Save Changes" class="btn" />
</form>

{% if request.user.id == user.id %}

<a href="{% url 'home:post_create' %}" class="btn btn-primary">Create New Post</a>
<a href="{% url 'accounts:edit_profile' %}" class="btn btn-primary">Edit Profile</a>

{% endif %}

{% if request.user.id != user.id and not is_following %}
<a href="{% url 'accounts:follow' user.id %}" class="btn btn-primary">Follow</a>
{% elif request.user.id != user.id and is_following %}
<a href="{% url 'accounts:unfollow' user.id %}" class="btn btn-primary"
  >Unfollow</a
>
{% endif %}

<div class="card">
  {% for post in posts %}
  <a class="card-body" href="{{ post.get_absolute_url }}"
    >{{ post.body|truncatewords:2 }}</a
  >
  {% endfor %}
</div>

{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load rest_framework %}

{% block content %}

<p class="text">Regissssterr</p>

<form action="" method="post" class="form-group text input-box ol-md-6" novalidate>
    {% csrf_token %}
    {% render_form form %}

    <input type="submit" value="Sign Up">
</form>

{% endblock %}