accounts/urls.py
from django.urls import path
from . import views
from rest_framework.authtoken import views as auth_token

app_name = 'accounts'
urlpatterns = [
    path('register/', views.UserReisterView.as_view(), name="register"),
    path('api-token-auth/', auth_token.obtain_auth_token),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('profile/<int:id>', views.UserProfileView.as_view(), name='profile'),
    path('reset/', views.UserResetPassword.as_view(), name='reset_password'),
    path('follow/<int:user_id>', views.UserFollowView.as_view(), name='follow'),
    path('unfollow/<int:user_id>', views.UserUnfollowView.as_view(), name='unfollow'),
    path('profile/', views.EditProfileView.as_view(), name='edit_profile'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('questions/', views.QuestionView.as_view(), name='questions'),
    path('questions/create/', views.QuestionCreateView.as_view(), name='questions'),
    path('questions/update/<int:pk>', views.QuestionUpdateView.as_view(), name='questions'),
    path('questions/delete/<int:pk>/', views.QuestionDeleteView.as_view(), name='questions'),

    ]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('home.urls'), name='home'),
    path('', include('accounts.urls'), name='accounts'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>BASE</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles/css/bootstrap.css' %}" />
    <link rel="stylesheet" href="{% static 'styles/css/responsive.css' %}" />

    <style>
        .navbar {
            background-color: aqua;
        }
        
        a {
            color: black;
            font-weight: 700;
            font-size: 20px;
        }
        
        .text {
            padding: 20px;
        }
        
        .input-box {
            width: 20vw;
        }
        
        .navbar {
            background-color: purple;
        }

        .btn {
            margin: 10px;
        }
    </style>

</head>

<style>
    .form-control {
        background-color: white;
    }
    .form-control:focus {
        background-color: white;
    }
</style>
<body>
    {% include 'navbar.html' %}
    {% include 'messages.html' %}
    {% block content %}

    {% endblock %}
</body>

</html>

templates/messages.html
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
            {{ message }}
        </li>
        {% endfor %}
    </ul>
{% endif %}

templates/navbar.html
<nav class='navbar navbar-expand-lg navbar-dark'>
<div class="navbar-nav text"> 
    <a class="navbar-brand" href="{% url 'home:home' %}">Home</a>

    {% if request.user.is_authenticated %}
    <a class="navbar-brand" href="">Profile</a> 
    <a class="navbar-brand" href="">Logout</a> 
    {% else %}
    <a class="navbar-brand" href="{% url 'accounts:login' %}">Login</a>
    <a class="navbar-brand" href="{% url 'accounts:register' %}">Register</a>
    {% endif %}  
</div>
</nav>